# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 15:02
from __future__ import unicode_literals

import {{cookiecutter.project_name}}.apps.accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0002_08_updates'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arn', models.CharField(blank=True, max_length=150, null=True)),
                ('device_token', models.CharField(max_length=250)),
                ('operational_system', model_utils.fields.StatusField(choices=[('iOS', 'iOS'), ('iOS_SANDBOX', 'iOS_SANDBOX'), ('Android', 'Android'), ('Web', 'Web')], db_index=True, default='iOS', max_length=100, no_check_for_status=True)),
                ('language', models.CharField(max_length=7)),
                ('access_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_token', to='oauth2_provider.AccessToken')),
                ('refresh_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refresh_token', to='oauth2_provider.RefreshToken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, {{cookiecutter.project_name}}.apps.accounts.models.DeviceMixin),
        ),
    ]
